#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5

// define pile
#define OBJECT_TYPE_PIPE 6

// define box
#define OBJECT_TYPE_BOX 7

// define ground
#define OBJECT_TYPE_GROUND 8

// define bush
#define OBJECT_TYPE_BUSH 9

// define cute cloud
#define OBJECT_TYPE_CLOUD_CUTE 10

// define block
#define OBJECT_TYPE_BLOCK 11

#define OBJECT_TYPE_PORTAL	50


#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 

#define ID_SPRITE_BRICK 20000

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_COIN 40000

#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)

// define id Pipe
#define ID_SPRITE_PIPE 60000
//#define ID_SPRITE_PIPE_TOP (ID_SPRITE_PIPE+1000)
//#define ID_SPRITE_PIPE_BOTTOM (ID_SPRITE_PIPE+2000)

#define ID_SPRITE_PIPE_TOP (ID_SPRITE_PIPE+1000)
#define ID_SPRITE_PIPE_TOP_LEFT (ID_SPRITE_PIPE_TOP+100)
#define ID_SPRITE_PIPE_TOP_RIGHT (ID_SPRITE_PIPE_TOP+200)

#define ID_SPRITE_PIPE_BOTTOM (ID_SPRITE_PIPE+2000)
#define ID_SPRITE_PIPE_BOTTOM_LEFT (ID_SPRITE_PIPE_BOTTOM+100)
#define ID_SPRITE_PIPE_BOTTOM_RIGHT	(ID_SPRITE_PIPE_BOTTOM+200)

// define id Koopas
#define ID_SPRITE_KOOPAS 70000
#define ID_SPRITE_KOOPAS_WALKING (ID_SPRITE_KOOPAS+1000)
#define ID_SPRITE_KOOPAS_WALKING_LEFT (ID_SPRITE_KOOPAS_WALKING+1)
#define ID_SPRITE_KOOPAS_DEAD (ID_SPRITE_KOOPAS+2001)

// define id Box
#define ID_SPRITE_BOX 80000

// white
#define ID_SPRITE_BOX_WHITE (ID_SPRITE_BOX+1000)
#define ID_SPRITE_BOX_WHITE_HEAD (ID_SPRITE_BOX_WHITE+100)
#define ID_SPRITE_BOX_WHITE_HEAD_LEFT (ID_SPRITE_BOX_WHITE_HEAD+10)
#define ID_SPRITE_BOX_WHITE_HEAD_MID (ID_SPRITE_BOX_WHITE_HEAD+20)
#define ID_SPRITE_BOX_WHITE_HEAD_RIGHT (ID_SPRITE_BOX_WHITE_HEAD+30)

#define ID_SPRITE_BOX_WHITE_BODY (ID_SPRITE_BOX_WHITE+200)
#define ID_SPRITE_BOX_WHITE_BODY_LEFT (ID_SPRITE_BOX_WHITE_BODY+10)
#define ID_SPRITE_BOX_WHITE_BODY_MID (ID_SPRITE_BOX_WHITE_BODY+20)
#define ID_SPRITE_BOX_WHITE_BODY_RIGHT (ID_SPRITE_BOX_WHITE_BODY+30)

#define ID_SPRITE_BOX_WHITE_FOOT (ID_SPRITE_BOX_WHITE+300)
#define ID_SPRITE_BOX_WHITE_FOOT_LEFT (ID_SPRITE_BOX_WHITE_FOOT+10)
#define ID_SPRITE_BOX_WHITE_FOOT_MID (ID_SPRITE_BOX_WHITE_FOOT+20)
#define ID_SPRITE_BOX_WHITE_FOOT_RIGHT (ID_SPRITE_BOX_WHITE_FOOT+30)

// green
#define ID_SPRITE_BOX_GREEN (ID_SPRITE_BOX+2000)
#define ID_SPRITE_BOX_GREEN_HEAD (ID_SPRITE_BOX_GREEN+100)
#define ID_SPRITE_BOX_GREEN_HEAD_LEFT (ID_SPRITE_BOX_GREEN_HEAD+10)
#define ID_SPRITE_BOX_GREEN_HEAD_MID (ID_SPRITE_BOX_GREEN_HEAD+20)
#define ID_SPRITE_BOX_GREEN_HEAD_RIGHT (ID_SPRITE_BOX_GREEN_HEAD+30)

#define ID_SPRITE_BOX_GREEN_BODY (ID_SPRITE_BOX_GREEN+200)
#define ID_SPRITE_BOX_GREEN_BODY_LEFT (ID_SPRITE_BOX_GREEN_BODY+10)
#define ID_SPRITE_BOX_GREEN_BODY_MID (ID_SPRITE_BOX_GREEN_BODY+20)
#define ID_SPRITE_BOX_GREEN_BODY_RIGHT (ID_SPRITE_BOX_GREEN_BODY+30)

#define ID_SPRITE_BOX_GREEN_FOOT (ID_SPRITE_BOX_GREEN+300)
#define ID_SPRITE_BOX_GREEN_FOOT_LEFT (ID_SPRITE_BOX_GREEN_FOOT+10)
#define ID_SPRITE_BOX_GREEN_FOOT_MID (ID_SPRITE_BOX_GREEN_FOOT+20)
#define ID_SPRITE_BOX_GREEN_FOOT_RIGHT (ID_SPRITE_BOX_GREEN_FOOT+30)

// pink
#define ID_SPRITE_BOX_PINK (ID_SPRITE_BOX+3000)
#define ID_SPRITE_BOX_PINK_HEAD (ID_SPRITE_BOX_PINK+100)
#define ID_SPRITE_BOX_PINK_HEAD_LEFT (ID_SPRITE_BOX_PINK_HEAD+10)
#define ID_SPRITE_BOX_PINK_HEAD_MID (ID_SPRITE_BOX_PINK_HEAD+20)
#define ID_SPRITE_BOX_PINK_HEAD_RIGHT (ID_SPRITE_BOX_PINK_HEAD+30)

#define ID_SPRITE_BOX_PINK_BODY (ID_SPRITE_BOX_PINK+200)
#define ID_SPRITE_BOX_PINK_BODY_LEFT (ID_SPRITE_BOX_PINK_BODY+10)
#define ID_SPRITE_BOX_PINK_BODY_MID (ID_SPRITE_BOX_PINK_BODY+20)
#define ID_SPRITE_BOX_PINK_BODY_RIGHT (ID_SPRITE_BOX_PINK_BODY+30)

#define ID_SPRITE_BOX_PINK_FOOT (ID_SPRITE_BOX_PINK+300)
#define ID_SPRITE_BOX_PINK_FOOT_LEFT (ID_SPRITE_BOX_PINK_FOOT+10)
#define ID_SPRITE_BOX_PINK_FOOT_MID (ID_SPRITE_BOX_PINK_FOOT+20)
#define ID_SPRITE_BOX_PINK_FOOT_RIGHT (ID_SPRITE_BOX_PINK_FOOT+30)

// blue
#define ID_SPRITE_BOX_BLUE (ID_SPRITE_BOX+4000)
#define ID_SPRITE_BOX_BLUE_HEAD (ID_SPRITE_BOX_BLUE+100)
#define ID_SPRITE_BOX_BLUE_HEAD_LEFT (ID_SPRITE_BOX_BLUE_HEAD+10)
#define ID_SPRITE_BOX_BLUE_HEAD_MID (ID_SPRITE_BOX_BLUE_HEAD+20)
#define ID_SPRITE_BOX_BLUE_HEAD_RIGHT (ID_SPRITE_BOX_BLUE_HEAD+30)

#define ID_SPRITE_BOX_BLUE_BODY (ID_SPRITE_BOX_BLUE+200)
#define ID_SPRITE_BOX_BLUE_BODY_LEFT (ID_SPRITE_BOX_BLUE_BODY+10)
#define ID_SPRITE_BOX_BLUE_BODY_MID (ID_SPRITE_BOX_BLUE_BODY+20)
#define ID_SPRITE_BOX_BLUE_BODY_RIGHT (ID_SPRITE_BOX_BLUE_BODY+30)

#define ID_SPRITE_BOX_BLUE_FOOT (ID_SPRITE_BOX_BLUE+300)
#define ID_SPRITE_BOX_BLUE_FOOT_LEFT (ID_SPRITE_BOX_BLUE_FOOT+10)
#define ID_SPRITE_BOX_BLUE_FOOT_MID (ID_SPRITE_BOX_BLUE_FOOT+20)
#define ID_SPRITE_BOX_BLUE_FOOT_RIGHT (ID_SPRITE_BOX_BLUE_FOOT+30)

// define id Ground
#define ID_SPRITE_GROUND 90000
#define ID_SPRITE_GROUND_TOP_LEFT (ID_SPRITE_GROUND+1000)
#define ID_SPRITE_GROUND_TOP_CEN (ID_SPRITE_GROUND+2000)
#define ID_SPRITE_GROUND_TOP_RIGHT (ID_SPRITE_GROUND+3000)
#define ID_SPRITE_GROUND_MID_LEFT (ID_SPRITE_GROUND+4000)
#define ID_SPRITE_GROUND_MID_CEN (ID_SPRITE_GROUND+5000)
#define ID_SPRITE_GROUND_MID_RIGHT (ID_SPRITE_GROUND+6000)

// define id Bush
#define ID_SPRITE_BUSH 100000
#define ID_SPRITE_BUSH_SMALL (ID_SPRITE_BUSH + 1000)
#define ID_SPRITE_BUSH_BIG (ID_SPRITE_BUSH + 2000)
#define ID_SPRITE_BUSH_BIG_TOP_LEFT (ID_SPRITE_BUSH_BIG + 100)
#define ID_SPRITE_BUSH_BIG_TOP_RIGHT (ID_SPRITE_BUSH_BIG + 200)
#define ID_SPRITE_BUSH_BIG_MID_LEFT (ID_SPRITE_BUSH_BIG + 300)
#define ID_SPRITE_BUSH_BIG_MID_RIGHT (ID_SPRITE_BUSH_BIG + 400)
#define ID_SPRITE_BUSH_BIG_BOTTOM_LEFT (ID_SPRITE_BUSH_BIG + 500)
#define ID_SPRITE_BUSH_BIG_BOTTOM_RIGHT (ID_SPRITE_BUSH_BIG + 600)
#define ID_SPRITE_BUSH_BIG_BODY (ID_SPRITE_BUSH_BIG + 700)

// define id Cloud Cute
#define ID_SPRITE_CLOUD_CUTE 110000
#define ID_SPRITE_CLOUD_CUTE_TOP (ID_SPRITE_CLOUD_CUTE + 1000)
#define ID_SPRITE_CLOUD_CUTE_TOP_LEFT (ID_SPRITE_CLOUD_CUTE_TOP + 100)
#define ID_SPRITE_CLOUD_CUTE_TOP_MID (ID_SPRITE_CLOUD_CUTE_TOP + 200)
#define ID_SPRITE_CLOUD_CUTE_TOP_RIGHT (ID_SPRITE_CLOUD_CUTE_TOP + 300)
#define ID_SPRITE_CLOUD_CUTE_BOTTOM (ID_SPRITE_CLOUD_CUTE + 2000)
#define ID_SPRITE_CLOUD_CUTE_BOTTOM_LEFT (ID_SPRITE_CLOUD_CUTE_BOTTOM + 100)
#define ID_SPRITE_CLOUD_CUTE_BOTTOM_MID (ID_SPRITE_CLOUD_CUTE_BOTTOM + 200)
#define ID_SPRITE_CLOUD_CUTE_BOTTOM_RIGHT (ID_SPRITE_CLOUD_CUTE_BOTTOM + 300)

// define id Block
#define ID_SPRITE_BLOCK 120000
