#pragma once
#include "GameObject.h"
#include "Mario.h"

#define VENUS_RED_BBOX_WIDTH 16
#define VENUS_RED_BBOX_HEIGHT 32

#define VENUS_GREEN_BBOX_WIDTH 16
#define VENUS_GREEN_BBOX_HEIGHT 24

#define PIRANHA_BBOX_WIDTH 16
#define PIRANHA_BBOX_HEIGHT 24


#define VENUS_STATE_MOVING_UP 100
#define VENUS_STATE_MOVING_DOWN 200
#define VENUS_STATE_AIMING 300
#define VENUS_STATE_FIRE 400

#define PIRANHA_MOVING 500

#define VENUS_TYPE_RED 1
#define VENUS_TYPE_GREEN 2
#define PIRANHA_TYPE 3

#define ID_ANI_VENUS_RED_LEFT_DOWN		15111
#define ID_ANI_VENUS_RED_LEFT_UP		15112
#define ID_ANI_VENUS_RED_RIGHT_DOWN		15121
#define ID_ANI_VENUS_RED_RIGHT_UP		15122

#define ID_ANI_VENUS_GREEN_LEFT_DOWN	15211
#define ID_ANI_VENUS_GREEN_LEFT_UP		15212
#define ID_ANI_VENUS_GREEN_RIGHT_DOWN	15221
#define ID_ANI_VENUS_GREEN_RIGHT_UP		15222

#define ID_ANI_PIRANHA_MOVING			15300
